import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CircleMarker, MapContainer, Polyline, Popup, TileLayer, useMap } from 'react-leaflet'
import { ChevronDown, ChevronUp, Clock3, MapPin, Navigation, Users } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { api, queryKeys } from '../../lib/api'
import 'leaflet/dist/leaflet.css'

type RouteStop = { kind: 'ORIGIN' | 'PICKUP' | 'DESTINATION'; label: string; address: string; latitude: number; longitude: number; friendName: string | null }
type RouteFeature = { id: string; properties: { title: string; originLabel: string; destinationLabel: string; status: string; departureAt: string; transportationMode: string; passengerCount: number; distanceMeters: number; durationSeconds: number; stops: RouteStop[] }; geometry: { type: 'LineString'; coordinates: [number, number][] } }
type MapData = { type: 'FeatureCollection'; features: RouteFeature[] }

export function MapPage() {
  const query = useQuery({ queryKey: queryKeys.map, queryFn: () => api<MapData>('/map') }); const [expanded, setExpanded] = useState(false); const [selectedId, setSelectedId] = useState<string | null>(null); const [fitRevision, setFitRevision] = useState(0)
  const features = query.data?.features ?? []; const selected = features.find((feature) => feature.id === selectedId) ?? features[0]
  useEffect(() => { if (!selectedId && features[0]) setSelectedId(features[0].id) }, [features, selectedId])
  return <main className="page map-page"><header className="page-header map-header"><div><p className="eyebrow">Routes nearby</p><h1>Trip map</h1></div><button className="icon-button" aria-label="Recenter selected route" onClick={() => setFitRevision((value) => value + 1)}><Navigation/></button></header>
    <div className="map-filters"><button className="active">My trips</button><button>Friends</button><button>This week</button></div>
    <section className="map-wrap">{query.isLoading ? <div className="map-loading">Loading routes…</div> : query.isError ? <div className="empty-state">Couldn’t load the map.</div> : features.length === 0 ? <div className="empty-state">No upcoming routes to show.</div> : <MapContainer center={[49.258, -122.955]} zoom={12} zoomControl={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"/>{features.map((feature) => <RouteLines key={feature.id} feature={feature} selected={feature.id === selected?.id}/>)}{selected?.properties.stops.map((stop, index) => <CircleMarker key={`${stop.kind}-${index}`} center={[stop.latitude, stop.longitude]} radius={stop.kind === 'PICKUP' ? 12 : 10} pathOptions={{ color: '#fffdfa', weight: 4, fillColor: stop.kind === 'PICKUP' ? '#f05d3b' : stop.kind === 'DESTINATION' ? '#167c63' : '#2536a8', fillOpacity: 1 }}><Popup><strong>{stop.label}</strong><br/>{stop.address}{stop.friendName && <><br/><small>{stop.kind === 'PICKUP' ? `Pickup for ${stop.friendName}` : stop.friendName}</small></>}</Popup></CircleMarker>)}{selected && <FitRoute feature={selected} revision={fitRevision}/>}</MapContainer>}</section>
    {selected && <section className={`route-drawer ${expanded ? 'expanded' : ''}`}><header><div><span className="event-icon"><MapPin/></span><span><strong>{selected.properties.originLabel} → {selected.properties.destinationLabel}</strong><small>{format(parseISO(selected.properties.departureAt), 'MMM d, h:mm a')} · {Math.round(selected.properties.durationSeconds / 60)} min · {(selected.properties.distanceMeters / 1000).toFixed(1)} km{selected.properties.passengerCount > 0 ? ` · ${selected.properties.passengerCount} passenger${selected.properties.passengerCount === 1 ? '' : 's'}` : ''}</small></span></div><button className="route-toggle" aria-label={expanded ? 'Collapse upcoming routes' : `Show ${features.length} upcoming routes`} onClick={() => setExpanded((value) => !value)}>{expanded ? <ChevronDown/> : <ChevronUp/>}</button></header>
      {expanded && <div className="route-list">{features.map((feature) => <button key={feature.id} className={feature.id === selected.id ? 'selected' : ''} onClick={() => { setSelectedId(feature.id); setExpanded(false) }}><span className="route-date"><strong>{format(parseISO(feature.properties.departureAt), 'MMM d')}</strong><small>{format(parseISO(feature.properties.departureAt), 'h:mm a')}</small></span><span className="route-copy"><small>From</small><strong>{feature.properties.originLabel}</strong><i/><small>To</small><strong>{feature.properties.destinationLabel}</strong><em><Clock3/>{Math.round(feature.properties.durationSeconds / 60)} min · {(feature.properties.distanceMeters / 1000).toFixed(1)} km {feature.properties.passengerCount > 0 && <><Users/>{feature.properties.passengerCount}</>}</em></span></button>)}</div>}
    </section>}
  </main>
}

function RouteLines({ feature, selected }: { feature: RouteFeature; selected: boolean }) { const positions = feature.geometry.coordinates.map(([longitude, latitude]) => [latitude, longitude] as [number, number]); return <>{selected && <Polyline positions={positions} pathOptions={{ color: '#fffdfa', weight: 15, opacity: 1 }}/>}<Polyline positions={positions} pathOptions={{ color: selected ? '#174cff' : '#87928e', weight: selected ? 9 : 3, opacity: selected ? 1 : .3, dashArray: selected ? '16 10' : undefined }}/></> }
function FitRoute({ feature, revision }: { feature: RouteFeature; revision: number }) { const map = useMap(); useEffect(() => { const points = feature.geometry.coordinates.map(([longitude, latitude]) => [latitude, longitude] as [number, number]); if (points.length > 1) map.fitBounds(points, { paddingTopLeft: [28, 40], paddingBottomRight: [28, 120] }) }, [feature, map, revision]); return null }
